[tool.black]
target-version = ['py37', 'py38']
exclude = '''
/(
    # Data
      checkpoints
    | data
    | results

    # Spack
    | \.spack-env

    # Python
    |  __pycache__
    | \.pytest_cache
    | \.mypy_cache

    # Git
    | \.git
)/
'''

[tool.mypy]
python_version = 3.7
ignore_missing_imports = True
warn_unused_configs = True
disallow_any_generics = True
#disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
no_implicit_reexport = True
strict_equality = True
