name: isort
on:
  push:
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/isort.yaml'
  pull_request:
    paths:
    - '**.py'
    - 'pyproject.toml'
    - '.github/workflows/isort.yaml'
jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run isort checks
      run: isort . --check --diff
