name: mypy
on:
  push:
    paths:
    - '**.py'
    - 'mypy.ini'
    - 'requirements.txt'
    - '.github/workflows/mypy.yaml'
  pull_request:
    paths:
    - '**.py'
    - 'mypy.ini'
    - 'requirements.txt'
    - '.github/workflows/mypy.yaml'
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install geos proj-bin
        # https://github.com/SciTools/cartopy/issues/1552
        pip install numpy
        pip install -r requirements.txt
    - name: Run mypy checks
      run: mypy .
