name: ruff
on: [push, pull_request]
jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run ruff checks
      run: |
        ruff check --output-format=github --no-fix .
        ruff format --diff
